// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGXIVCD3YLxscrhK0BwADqr3kfqfAvsQ',
    appId: '1:511143004946:web:131563d48d7cee758101cb',
    messagingSenderId: '511143004946',
    projectId: 'cepu-app-b28f5',
    authDomain: 'cepu-app-b28f5.firebaseapp.com',
    databaseURL: 'https://cepu-app-b28f5-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-b28f5.firebasestorage.app',
    measurementId: 'G-NRQLN4J9NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPwPPCpKEJZOBwBL_AB2cvCDa7e72sSBY',
    appId: '1:511143004946:android:c537aabb69f888c68101cb',
    messagingSenderId: '511143004946',
    projectId: 'cepu-app-b28f5',
    databaseURL: 'https://cepu-app-b28f5-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-b28f5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhGXIVCD3YLxscrhK0BwADqr3kfqfAvsQ',
    appId: '1:511143004946:web:11688da657130a028101cb',
    messagingSenderId: '511143004946',
    projectId: 'cepu-app-b28f5',
    authDomain: 'cepu-app-b28f5.firebaseapp.com',
    databaseURL: 'https://cepu-app-b28f5-default-rtdb.firebaseio.com',
    storageBucket: 'cepu-app-b28f5.firebasestorage.app',
    measurementId: 'G-E5WVS3FQMQ',
  );

}