// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsIPE-HwC-LDBwcxlZLU_w5j42gPYnreo',
    appId: '1:606802107022:web:30642b424166cf80ca87df',
    messagingSenderId: '606802107022',
    projectId: 'kisi-kisi-uts-2e404',
    authDomain: 'kisi-kisi-uts-2e404.firebaseapp.com',
    databaseURL: 'https://kisi-kisi-uts-2e404-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2e404.firebasestorage.app',
    measurementId: 'G-GD3ZZ1CKM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC-14V2b7CgZsQD9rxUbN0vVhqgO9IPss',
    appId: '1:606802107022:android:a245c6e1d7ab7fb0ca87df',
    messagingSenderId: '606802107022',
    projectId: 'kisi-kisi-uts-2e404',
    databaseURL: 'https://kisi-kisi-uts-2e404-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2e404.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsIPE-HwC-LDBwcxlZLU_w5j42gPYnreo',
    appId: '1:606802107022:web:9d2f9d4d21afa824ca87df',
    messagingSenderId: '606802107022',
    projectId: 'kisi-kisi-uts-2e404',
    authDomain: 'kisi-kisi-uts-2e404.firebaseapp.com',
    databaseURL: 'https://kisi-kisi-uts-2e404-default-rtdb.firebaseio.com',
    storageBucket: 'kisi-kisi-uts-2e404.firebasestorage.app',
    measurementId: 'G-BHV8W0004N',
  );
}
